# Generated by Django 6.1 on 2026-08-26 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_pr_exercises', models.JSONField(default=list)),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=3)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=1, help_text='Current body weight', max_digits=5, null=True)),
                ('goal_weight', models.DecimalField(blank=True, decimal_places=1, help_text='Target body weight', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
