# Generated by Django 6.1 on 2026-08-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0003_personalrecord_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrecord',
            name='workout',
        ),
    ]
