# Generated by Django 6.1 on 2026-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0005_personalrecord_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrecord',
            name='workout',
        ),
    ]
