# Generated by Django 6.1 on 2026-08-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0006_remove_personalrecord_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitnessapp.workout'),
        ),
    ]
